<a href="https://colab.research.google.com/github/yash121299/PyTorch_Learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Python Fundamentals

Reference Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
# Using No GPU
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# Using a GPU
!nvidia-smi

Mon Feb 24 06:40:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [88]:
# Importing Libraries. Colab comes with common ML/Deep Learning libraries installed
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


## Tensors
### Creating Tensors

Pytorch tensors are created using `torch.Tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [3]:
#Scalar
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [6]:
# ndim - number of dimensions - Scalar is just a value. Number of Dimensions = 0 (Its not 1-D or 2-D. just a value)
scalar.ndim

0

In [7]:
# Get tensor back as a Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])

In [9]:
vector

tensor([7, 7])

In [11]:
# Just a vector in 1 D - Number of dimensions can be thought of as number of square brackers
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX[0]

tensor([7, 8])

In [22]:
MATRIX[1]

tensor([ 9, 10])

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [32]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [33]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [35]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [36]:
TENSOR.ndim

3

In [37]:
TENSOR.shape

torch.Size([2, 3, 3])

In [42]:
TENSOR[0],TENSOR[1]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### Random Tensors

Why Random Tensors?
Random Tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers and so on`

torch.rand Documentation -> https://pytorch.org/docs/main/generated/torch.rand.html


In [89]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [90]:
random_tensor

tensor([[0.5787, 0.7326, 0.5543, 0.2240],
        [0.2245, 0.4633, 0.8032, 0.6002],
        [0.9271, 0.0109, 0.3066, 0.9006]])

In [91]:
random_tensor.ndim

2

In [92]:
random_tensor = torch.rand(1,3,4)

In [93]:
random_tensor

tensor([[[0.0854, 0.1667, 0.5905, 0.7971],
         [0.3834, 0.1249, 0.5337, 0.2900],
         [0.8417, 0.8159, 0.0374, 0.8243]]])

In [94]:
random_tensor.ndim

3

In [95]:
random_tensor.shape

torch.Size([1, 3, 4])

In [96]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (230,230,3)) # height, width, color channels (R,G,B)

In [97]:
random_image_tensor.shape

torch.Size([230, 230, 3])

In [98]:
random_image_tensor.ndim

3

In [99]:
# The size attribute is taken as default

In [100]:
torch.rand(3,3)

tensor([[0.4564, 0.8882, 0.5401],
        [0.1892, 0.9504, 0.8883],
        [0.1482, 0.3661, 0.7772]])

In [101]:
torch.rand(size=(3,3))

tensor([[0.2283, 0.3924, 0.2364],
        [0.8476, 0.8906, 0.0441],
        [0.8389, 0.5961, 0.1717]])

### Tensors of Zeroes and Ones

In [102]:
# Create a tensor of all zeroes (Used when creating a mask)
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [103]:
zeros*random_tensor # Can be used to set some specific columns or part of a tensor to zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [104]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [105]:
# Get the datatype of a tensor - float32 is default
ones.dtype

torch.float32

In [106]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like some other tensor

In [107]:
# torch.range() - Will be deprecated, preferably use arange()
torch.range(1,11)

<ipython-input-107-2023246c8776>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [108]:
torch.arange(1,11) # works like python range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Documentation for torch.arange() -> https://pytorch.org/docs/stable/generated/torch.arange.html

In [109]:
one_to_ten = torch.arange(start = 0,end = 1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [110]:
one_to_ten = torch.arange(start = 1,end = 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
# Creating Tensors like - replicate the shape of another tensor - zeros_like, ones_like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

 ### Tensor Datatypes

 All Datatypes are mentioned here -> https://pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorch & Deep Learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device


 Precision in Computing (How many bits) - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [121]:
# Float 32 tensor - Default for floating point
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)

In [122]:
float_32_tensor.dtype

torch.float32

In [123]:
# Int 64 tensor - Default for integer values
int_64_tensor = torch.tensor([3,6,9],dtype=None)

In [124]:
int_64_tensor.dtype

torch.int64

In [126]:
# Specifying type
float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)

In [127]:
float_16_tensor.dtype

torch.float16

In [129]:
# Important params for creating tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # Device on which the tensor is present, default is "cpu". If GPU is present, can move tensor there using "cuda"
                               requires_grad=False) # Want pytorch to track gradients for the tensor operations

In [130]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [131]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [133]:
resultant_tensor = float_16_tensor * float_32_tensor

In [134]:
resultant_tensor

tensor([ 9., 36., 81.])

In [135]:
resultant_tensor.dtype

torch.float32