<a href="https://colab.research.google.com/github/yash121299/PyTorch_Learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Reference Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
# Using No GPU
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
 # Using a GPU
!nvidia-smi

Fri May 30 18:40:45 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# Importing Libraries. Colab comes with common ML/Deep Learning libraries installed
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


## Tensors
### Creating Tensors

Pytorch tensors are created using `torch.Tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [3]:
#Scalar
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
# ndim - number of dimensions - Scalar is just a value. Number of Dimensions = 0 (Its not 1-D or 2-D. just a value)
scalar.ndim

0

In [6]:
# Get tensor back as a Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])

In [8]:
vector

tensor([7, 7])

In [9]:
# Just a vector in 1 D - Number of dimensions can be thought of as number of square brackers
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [20]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([2, 3, 3])

In [23]:
TENSOR[0],TENSOR[1]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### Random Tensors

Why Random Tensors?
Random Tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers and so on`

torch.rand Documentation -> https://pytorch.org/docs/main/generated/torch.rand.html


In [24]:
# Create a random tensor of size (3,4) -  Values range from 0 to 1
random_tensor = torch.rand(3,4)

In [25]:
random_tensor

tensor([[0.2560, 0.9731, 0.6884, 0.2567],
        [0.1315, 0.0912, 0.1501, 0.2858],
        [0.2366, 0.7097, 0.2488, 0.5817]])

In [26]:
random_tensor.ndim

2

In [27]:
random_tensor = torch.rand(1,3,4)

In [28]:
random_tensor

tensor([[[0.1213, 0.5283, 0.8730, 0.2292],
         [0.5340, 0.8592, 0.2550, 0.4073],
         [0.7866, 0.1329, 0.1133, 0.5568]]])

In [29]:
random_tensor.ndim

3

In [30]:
random_tensor.shape

torch.Size([1, 3, 4])

In [31]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (230,230,3)) # height, width, color channels (R,G,B)

In [32]:
random_image_tensor.shape

torch.Size([230, 230, 3])

In [33]:
random_image_tensor.ndim

3

In [34]:
# The size attribute is taken as default

In [35]:
torch.rand(3,3)

tensor([[0.5139, 0.5844, 0.8549],
        [0.7931, 0.6750, 0.3818],
        [0.5542, 0.8962, 0.7640]])

In [36]:
torch.rand(size=(3,3))

tensor([[0.2782, 0.5537, 0.1364],
        [0.1552, 0.8877, 0.8664],
        [0.8820, 0.7365, 0.8631]])

### Tensors of Zeroes and Ones

In [37]:
# Create a tensor of all zeroes (Used when creating a mask)
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
zeros*random_tensor # Can be used to set some specific columns or part of a tensor to zero. Like a mask in CV

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [39]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
# Get the datatype of a tensor - float32 is default
ones.dtype

torch.float32

In [41]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like some other tensor

In [42]:
# torch.range() - Will be deprecated, preferably use arange()
torch.range(1,11)

<ipython-input-42-2023246c8776>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [43]:
torch.arange(1,11) # works like python range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Documentation for torch.arange() -> https://pytorch.org/docs/stable/generated/torch.arange.html

In [44]:
one_to_ten = torch.arange(start = 0,end = 1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [45]:
one_to_ten = torch.arange(start = 1,end = 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
# Creating Tensors like - replicate the shape of another tensor - zeros_like, ones_like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
# input is by default but can be mentioned
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

 ### Tensor Datatypes

 All Datatypes are mentioned here -> https://pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device


 Precision in Computing (How many bits) - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [49]:
# Float 32 tensor - Default for floating point
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)

In [50]:
float_32_tensor.dtype

torch.float32

In [51]:
# Int 64 tensor - Default for integer values
int_64_tensor = torch.tensor([3,6,9],dtype=None)

In [52]:
int_64_tensor.dtype

torch.int64

In [53]:
# Specifying type
float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)

In [54]:
float_16_tensor.dtype

torch.float16

In [55]:
# Important params for creating tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor (e.g. torch.float32 or torch.float16)
                               device=None, # Device on which the tensor is present, default is "cpu". If GPU is present, can move tensor there using "cuda"
                               requires_grad=False) # Want pytorch to track gradients for the tensor operations

In [56]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [57]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

While multiplying 2 different datatype tensor, torch will make them a type that will give us least lossy conversion or throw an error

In [58]:
resultant_tensor = float_16_tensor * float_32_tensor

In [59]:
resultant_tensor

tensor([ 9., 36., 81.])

In [60]:
resultant_tensor.dtype

torch.float32

In [61]:
long_tensor = torch.tensor([3,6,9],dtype=torch.long)

In [62]:
long_tensor

tensor([3, 6, 9])

In [63]:
long_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [64]:
(long_tensor*float_32_tensor).dtype

torch.float32

### Getting information from tensors

1. Datatype - `tensor.dtype`
2. Shape - `tensor.shape`
3. Device - `tensor.device`

In [65]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4322, 0.4533, 0.0766, 0.8337],
        [0.5470, 0.6346, 0.6893, 0.1022],
        [0.4527, 0.0501, 0.0918, 0.0221]])

In [66]:
some_tensor.dtype

torch.float32

In [67]:
some_tensor.shape

torch.Size([3, 4])

In [68]:
# Returns the same thing but is a function instead of an attribute
some_tensor.size()

torch.Size([3, 4])

In [69]:
some_tensor.device

device(type='cpu')

In [70]:
# Details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4322, 0.4533, 0.0766, 0.8337],
        [0.5470, 0.6346, 0.6893, 0.1022],
        [0.4527, 0.0501, 0.0918, 0.0221]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensor (tensor operation)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [71]:
# Creating a tensor
my_tensor = torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

In [72]:
#Adding 10 to a  tensor
my_tensor+10

tensor([11, 12, 13])

In [73]:
# Multiplying a tensor by 10 (Called Element wise multiplication)
my_tensor*10

tensor([10, 20, 30])

In [83]:
# Also element wise multiplication
my_tensor*my_tensor

tensor([1, 4, 9])

In [84]:
# Since we didnt reassign the tensor it stays the same
my_tensor

tensor([1, 2, 3])

In [85]:
# Subtraction by 10
my_tensor - 10

tensor([-9, -8, -7])

In [86]:
# Division by 10
my_tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [87]:
# Can also use inbuilt pytorch functions
torch.mul(my_tensor,10)

tensor([10, 20, 30])

In [88]:
torch.add(my_tensor,10)

tensor([11, 12, 13])

In [89]:
torch.sub(my_tensor,10)

tensor([-9, -8, -7])

In [90]:
torch.div(my_tensor,10)

tensor([0.1000, 0.2000, 0.3000])

In [81]:
(torch.div(my_tensor,10)).dtype

torch.float32

### Matrix Multiplication (also called dot product)
 2 main ways of performing matrix multiplication in neural networks and deep learning
 1. Element wise multiplication
 2. Matrix multiplication (dot product)

 Info on Matrix Multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

 2 main rules to satisfy for matrix multiplication:

  The **inner dimensions** must match:
 * `(3,2) @ (3,2)` wont work
 * `(2,3) @ (3,2)` will work
 * `(3,2) @ (2,3)` will work

  Resulting matrix has the shape of the **outer dimensions**
 * `(2,3) @ (3,2)` -> `(2,2)`
 * `(3,2) @ (2,3)` -> `(3,3)`


 Matrix multiplication visualization: http://matrixmultiplication.xyz/

In [91]:
# Element wise multiplication
print(f"{my_tensor} * {my_tensor}")
print(f"Equals: {my_tensor* my_tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [92]:
# Matrix multiplication
# Pytorch function is vectorized so its way faster
torch.matmul(my_tensor,my_tensor)

tensor(14)

In [96]:
# Can also use the '@' operator
my_tensor @ my_tensor

tensor(14)

In [97]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.7859, 1.3419],
        [0.5833, 0.9313]])

In [98]:
# Throws error
torch.matmul(torch.rand(2,3),torch.rand(2,3))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [99]:
%%time
torch.matmul(my_tensor,my_tensor)

CPU times: user 375 µs, sys: 51 µs, total: 426 µs
Wall time: 351 µs


tensor(14)

In [100]:
%%time
val = 0
for i in range(len(my_tensor)):
  val+= my_tensor[i] * my_tensor[i]
print(val)

tensor(14)
CPU times: user 1.3 ms, sys: 0 ns, total: 1.3 ms
Wall time: 1.43 ms


### One of the most common errors in deep learning: shape errors

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
# torch.matmul is the same as torch.mm (is an alias)
# will throw shape error
torch.mm(tensor_A,tensor_B)

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

Now we can multiply since the inner dimensions are the same

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor aggregation - Finding the min,max,mean,sum,etc of a tensor

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Finding min - 2 ways
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
# Finding max - 2 ways
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
# Finding the mean - Doesnt work with tensor of type int/long.
# So we convert the tensor to floating point datatype before calculating the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum - 2 ways
torch.sum(x),x.sum()

(tensor(450), tensor(450))

## Finding positional min and max

In [ ]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Gives the index of the minimum value
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Gives the index of the maximum . Used for softmax activation
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensor
* Reshaping - Reshapes an input tensor to a specified shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor (Shows same tensor from a different perspective)
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Creating a tensor
x = torch.arange(1.,10.)

In [ ]:
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Reshape - Add extra dimension
# The new dimensions still need to be compatible, we cant write x.reshape(1,7), because x has 9 values it wont work
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped_2 = x.reshape(9,1)
x_reshaped_2,x_reshaped_2.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Original x is not modified
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Change the view
# Same as reshape but shared memory with x
# Modifying z will reshult in x being modified
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Modifying first element to 5
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
# default dim=0
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [ ]:
# hstack puts the tensors side by side and makes them a single dimension
torch.hstack([x,x,x])

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# vstack is same as dim=0, stacks the tensors on top of each other
torch.vstack([x,x,x])

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped, x_reshaped.size()

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Removed all 1 dimensions (1,9)  to (9)
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a  single dimension to a target tensor at a specific dimension (dim)
x_reshaped.unsqueeze(dim=1) , x_reshaped.unsqueeze(dim=1).shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]), torch.Size([1, 1, 9]))

In [ ]:
x_reshaped.unsqueeze(dim=2) , x_reshaped.unsqueeze(dim=2).shape

(tensor([[[5.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [ ]:
x_original = torch.rand(size=(224,224,3)) # [height,width,color_channels]
x_original.shape

torch.Size([224, 224, 3])

In [ ]:
# torch.permute - Rearrange the dimensions of the tensor in the specified way
# This returns a view - same place in memory but a different view
x_permuted = x_original.permute(2,0,1) # Shifts axis 0->1,1->2,2->0
x_permuted.shape # [color channels,height,width]

torch.Size([3, 224, 224])

In [ ]:
x_original[0,0,0] = 1.1

In [ ]:
x_permuted[0,0,0] # Because its a view

tensor(1.1000)

## Indexing (selecting data from a tensor)

Indexing in PyTorch is similar to Numpy

In [ ]:
# Creating a tensor
x = torch.arange(1.,10.).reshape(1,3,3)
x,x.size()

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x[0,0],x[0][0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [ ]:
x[0,1],x[0][1]

(tensor([4., 5., 6.]), tensor([4., 5., 6.]))

In [ ]:
x[0,0,0]

tensor(1.)

In [ ]:
x[0,2,2]

tensor(9.)

In [ ]:
# You can use semicolon ":" to select all of the dimension
x[0,0,:]

tensor([1., 2., 3.])

In [ ]:
x[:,:,1] # Get all values of the 0th and 1st dimension but ony index 1 of 2nd dimension

tensor([[2., 5., 8.]])

In [ ]:
x[:,1,1],x[0,1,1] # Note that because we are selecting all of the first dimension we get a square bracket

(tensor([5.]), tensor(5.))

In [ ]:
x[0,:,2]

tensor([3., 6., 9.])

## PyTorch tensors & Numpy
(Pytorch requires numpy to work)

Numpy is a popular scientific Python numerical computing library.
Because of this, PyTorch has functionality to interact with it
* Data in NumPy -> want it in PyTorch tensor => `torch.from_numpy(ndarray)`
* PyTorch tensor -> numpy array => `torch.Tensor.numpy()`

Documentation links:
https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html
https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

In [ ]:
# Numpy Array to tensor
import torch
import numpy as np

np_array = np.arange(1.0,8.0)
converted_tensor = torch.from_numpy(np_array)
np_array,converted_tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Default type for a numpy array - float64
np_array.dtype

dtype('float64')

In [ ]:
# Converted tensor has dtype also as float64 although in torch the default type is float32
converted_tensor.dtype

torch.float64

In [ ]:
np_array[0] = 99.9
np_array, converted_tensor

(array([99.9,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ]),
 tensor([99.9000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  7.0000],
        dtype=torch.float64))

In [ ]:
np_array = np.arange(1.0,8.0)
converted_tensor = torch.from_numpy(np_array)
np_array = np_array+1
np_array, converted_tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
np_array

array([2., 3., 4., 5., 6., 7., 8.])

In [ ]:
# Tensor to Numpy array
onez_tensor = torch.ones(7)
onez_tensor , onez_tensor.size()

(tensor([1., 1., 1., 1., 1., 1., 1.]), torch.Size([7]))

In [ ]:
numpy_tensor = onez_tensor.numpy()
numpy_tensor, numpy_tensor.shape

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32), (7,))

In [ ]:
onez_tensor.dtype , numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [ ]:
onez_tensor = onez_tensor + 1
onez_tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
onez_tensor = torch.ones(7)
numpy_tensor = onez_tensor.numpy()
onez_tensor[0] = 55
onez_tensor,numpy_tensor

(tensor([55.,  1.,  1.,  1.,  1.,  1.,  1.]),
 array([55.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32))

As seen above, in some cases updating the tensor results in numpy array being changed too (also in some cases updating the numpy array changes the tensor too). Look at this question for more details on when they change and when they dont:
https://www.udemy.com/course/pytorch-for-deep-learning/learn/lecture/32668444#questions/18895530

Scroll below the video to the question and the responses to get a better understanding of when the numpy array and tensor share memory
