<a href="https://colab.research.google.com/github/yash121299/PyTorch_Learning/blob/main/00_Pytorch_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(size=(7,7))
tensor_A

tensor([[0.9379, 0.4358, 0.9895, 0.2134, 0.8484, 0.1264, 0.2278],
        [0.9703, 0.1056, 0.4268, 0.9841, 0.4523, 0.1577, 0.4242],
        [0.6036, 0.9553, 0.2730, 0.5213, 0.7299, 0.5837, 0.2062],
        [0.6597, 0.2004, 0.2337, 0.7062, 0.9090, 0.8669, 0.1842],
        [0.4299, 0.0873, 0.3475, 0.7113, 0.8407, 0.4016, 0.5196],
        [0.4728, 0.5923, 0.0244, 0.2329, 0.8605, 0.5016, 0.8055],
        [0.9818, 0.3291, 0.4821, 0.2806, 0.6465, 0.6874, 0.6274]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tensor_B = torch.rand(size=(1,7))
print(tensor_B)
# Perform matrix multiplication
result = torch.matmul(tensor_A,tensor_B.T)
result

tensor([[0.7547, 0.4425, 0.2896, 0.4174, 0.7103, 0.8393, 0.6394]])


tensor([[2.1308],
        [2.0383],
        [2.3151],
        [2.4400],
        [2.0271],
        [2.2704],
        [2.5806]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_C = torch.rand(size=(7,7))
tensor_D = torch.rand(size=(1,7))

# Matrix multiply tensors
result = torch.matmul(tensor_C,tensor_D.T)
result

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tensor_E = torch.rand(size=(2,3))
tensor_E = tensor_E.to(device)
tensor_F = torch.rand(size=(2,3))
tensor_F = tensor_F.to(device)
tensor_E,tensor_F

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor_E,tensor_F.T)
result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(result.max(),torch.max(result))
# Find min
print(result.min(),torch.min(result))

tensor(0.5617, device='cuda:0') tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0') tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(result.argmax())

# Find arg min
print(result.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))

print(random_tensor,random_tensor.shape)

# Remove single dimensions
squeezed_random_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
print(squeezed_random_tensor,squeezed_random_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
