<a href="https://colab.research.google.com/github/yash121299/PyTorch_Learning/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Python Fundamentals

Reference Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
# Using No GPU
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# Using a GPU
!nvidia-smi

Mon Feb 24 06:40:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [1]:
# Importing Libraries. Colab comes with common ML/Deep Learning libraries installed
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


## Tensors
### Creating Tensors

Pytorch tensors are created using `torch.Tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [ ]:
#Scalar
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
# ndim - number of dimensions - Scalar is just a value. Number of Dimensions = 0 (Its not 1-D or 2-D. just a value)
scalar.ndim

0

In [ ]:
# Get tensor back as a Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
# Just a vector in 1 D - Number of dimensions can be thought of as number of square brackers
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0],TENSOR[1]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### Random Tensors

Why Random Tensors?
Random Tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers and so on`

torch.rand Documentation -> https://pytorch.org/docs/main/generated/torch.rand.html


In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.7645, 0.8380, 0.1914, 0.1391],
        [0.7213, 0.9879, 0.6621, 0.2804],
        [0.4993, 0.9891, 0.4884, 0.2647]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor = torch.rand(1,3,4)

In [ ]:
random_tensor

tensor([[[0.2147, 0.9617, 0.1837, 0.5190],
         [0.0138, 0.7689, 0.7103, 0.9659],
         [0.8343, 0.1018, 0.7768, 0.9897]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([1, 3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (230,230,3)) # height, width, color channels (R,G,B)

In [ ]:
random_image_tensor.shape

torch.Size([230, 230, 3])

In [ ]:
random_image_tensor.ndim

3

In [ ]:
# The size attribute is taken as default

In [ ]:
torch.rand(3,3)

tensor([[0.2498, 0.4019, 0.0388],
        [0.2398, 0.9532, 0.0612],
        [0.2126, 0.1959, 0.0932]])

In [ ]:
torch.rand(size=(3,3))

tensor([[0.6463, 0.6893, 0.0331],
        [0.8288, 0.0513, 0.9565],
        [0.8928, 0.3652, 0.3825]])

### Tensors of Zeroes and Ones

In [ ]:
# Create a tensor of all zeroes (Used when creating a mask)
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor # Can be used to set some specific columns or part of a tensor to zero

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# Get the datatype of a tensor - float32 is default
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like some other tensor

In [ ]:
# torch.range() - Will be deprecated, preferably use arange()
torch.range(1,11)

<ipython-input-156-2023246c8776>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
torch.arange(1,11) # works like python range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Documentation for torch.arange() -> https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
one_to_ten = torch.arange(start = 0,end = 1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
one_to_ten = torch.arange(start = 1,end = 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating Tensors like - replicate the shape of another tensor - zeros_like, ones_like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

 ### Tensor Datatypes

 All Datatypes are mentioned here -> https://pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 big error you'll run into with PyTorch & Deep Learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on right device


 Precision in Computing (How many bits) - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor - Default for floating point
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Int 64 tensor - Default for integer values
int_64_tensor = torch.tensor([3,6,9],dtype=None)

In [ ]:
int_64_tensor.dtype

torch.int64

In [ ]:
# Specifying type
float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
# Important params for creating tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                               device=None, # Device on which the tensor is present, default is "cpu". If GPU is present, can move tensor there using "cuda"
                               requires_grad=False) # Want pytorch to track gradients for the tensor operations

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

While multiplying 2 datatype tensor, torch will make them a type that will give us least lossy conversion or throw an error

In [ ]:
resultant_tensor = float_16_tensor * float_32_tensor

In [ ]:
resultant_tensor

tensor([ 9., 36., 81.])

In [ ]:
resultant_tensor.dtype

torch.float32

In [ ]:
long_tensor = torch.tensor([3,6,9],dtype=torch.long)

In [ ]:
long_tensor

tensor([3, 6, 9])

In [ ]:
long_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Datatype - `tensor.dtype`
2. Shape - `tensor.shape`
3. Device - `tensor.device`

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0677, 0.4369, 0.2281, 0.2804],
        [0.2726, 0.4705, 0.6589, 0.8364],
        [0.0077, 0.6774, 0.6864, 0.1669]])

In [ ]:
some_tensor.dtype

torch.float32

In [ ]:
some_tensor.shape

torch.Size([3, 4])

In [ ]:
# Returns the same thing but is a function instead of an attribute
some_tensor.size()


torch.Size([3, 4])

In [ ]:
some_tensor.device

device(type='cpu')

In [ ]:
# Details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0677, 0.4369, 0.2281, 0.2804],
        [0.2726, 0.4705, 0.6589, 0.8364],
        [0.0077, 0.6774, 0.6864, 0.1669]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensor (tensor operation)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [ ]:
# Creating a tensor
my_tensor = torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

In [ ]:
#Adding 10 to a  tensor
my_tensor+10

tensor([11, 12, 13])

In [ ]:
# Multiplying a tensor by 10 (Called Element wise multiplication)
my_tensor*10

tensor([10, 20, 30])

In [ ]:
# Since we didnt reassign the tensor it stays the same
my_tensor

tensor([1, 2, 3])

In [ ]:
# Subtraction by 10
my_tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Division by 10
my_tensor/10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Can also use inbuilt pytorch functions
torch.mul(my_tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(my_tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.sub(my_tensor,10)

tensor([-9, -8, -7])

In [ ]:
torch.div(my_tensor,10)

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication (also called dot product)
 2 main ways of performing matrix multiplication in neural networks and deep learning
 1. Element wise multiplication
 2. Matrix multiplication (dot product)

 Info on Matrix Multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

 2 main rules to satisfy for matrix multiplication:

  The **inner dimensions** must match:
 * `(3,2) @ (3,2)` wont work
 * `(2,3) @ (3,2)` will work
 * `(3,2) @ (2,3)` will work

  Resulting matrix has the shape of the **outer dimensions**
 * `(2,3) @ (3,2)` -> `(2,2)`
 * `(3,2) @ (2,3)` -> `(3,3)`


 Matrix multiplication visualization: http://matrixmultiplication.xyz/

In [ ]:
# Element wise multiplication
print(f"{my_tensor} * {my_tensor}")
print(f"Equals: {my_tensor* my_tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
# Pytorch function is vectorized so its way faster
torch.matmul(my_tensor,my_tensor)

tensor(14)

In [ ]:
my_tensor @ my_tensor

tensor(14)

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.7195, 1.3069],
        [0.4733, 0.5013]])

In [ ]:
# Throws error
torch.matmul(torch.rand(2,3),torch.rand(2,3))

In [ ]:
%%time
torch.matmul(my_tensor,my_tensor)

CPU times: user 505 µs, sys: 0 ns, total: 505 µs
Wall time: 394 µs


tensor(14)

In [ ]:
%%time
val = 0
for i in range(len(my_tensor)):
  val+= my_tensor[i] * my_tensor[i]
print(val)

tensor(14)
CPU times: user 2.09 ms, sys: 0 ns, total: 2.09 ms
Wall time: 1.74 ms


### One of the most common errors in deep learning: shape errors

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
# torch.matmul is the same as torch.mm (is an alias)
# will throw shape error
torch.mm(tensor_A,tensor_B)

In [ ]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

Now we can multiply since the inner dimensions are the same

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Tensor aggregation - Finding the min,max,mean,sum,etc of a tensor

In [7]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [8]:
# Finding min - 2 ways
torch.min(x),x.min()

(tensor(0), tensor(0))

In [9]:
# Finding max - 2 ways
torch.max(x),x.max()

(tensor(90), tensor(90))

In [12]:
# Finding the mean - Doesnt work with tensor of type int/long.
# So we convert the tensor to floating point datatype before calculating the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [13]:
# Find the sum - 2 ways
torch.sum(x),x.sum()

(tensor(450), tensor(450))

## Finding positional min and max

In [18]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [19]:
# Gives the index of the minimum value
x.argmin()

tensor(0)

In [21]:
x[0]

tensor(1)

In [20]:
# Gives the index of the maximum . Used for softmax activation
x.argmax()

tensor(9)

In [22]:
x[9]

tensor(91)