## 00. Python Fundamentals

Reference Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
# Using No GPU
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
# Using a GPU
!nvidia-smi

Mon Feb 24 06:40:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
# Importing Libraries. Colab comes with common ML/Deep Learning libraries installed
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


## Tensors
### Creating Tensors

Pytorch tensors are created using `torch.Tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [3]:
#Scalar
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [6]:
# ndim - number of dimensions - Scalar is just a value. Number of Dimensions = 0 (Its not 1-D or 2-D. just a value)
scalar.ndim

0

In [7]:
# Get tensor back as a Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])

In [9]:
vector

tensor([7, 7])

In [11]:
# Just a vector in 1 D - Number of dimensions can be thought of as number of square brackers
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX[0]

tensor([7, 8])

In [22]:
MATRIX[1]

tensor([ 9, 10])

In [23]:
MATRIX.shape

torch.Size([2, 2])

In [32]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [33]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [35]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [36]:
TENSOR.ndim

3

In [37]:
TENSOR.shape

torch.Size([2, 3, 3])

In [42]:
TENSOR[0],TENSOR[1]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

### Random Tensors

Why Random Tensors?
Random Tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers and so on`

torch.rand Documentation -> https://pytorch.org/docs/main/generated/torch.rand.html


In [48]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [49]:
random_tensor

tensor([[0.9946, 0.1653, 0.0705, 0.9069],
        [0.3517, 0.3776, 0.2110, 0.6948],
        [0.2439, 0.9120, 0.4874, 0.9841]])

In [50]:
random_tensor.ndim

2

In [51]:
random_tensor = torch.rand(1,3,4)

In [52]:
random_tensor

tensor([[[0.4970, 0.0239, 0.1518, 0.1918],
         [0.3306, 0.2889, 0.1025, 0.0439],
         [0.1383, 0.1734, 0.3668, 0.7734]]])

In [53]:
random_tensor.ndim

3

In [55]:
random_tensor.shape

torch.Size([1, 3, 4])

In [59]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (230,230,3)) # height, width, color channels (R,G,B)

In [60]:
random_image_tensor.shape

torch.Size([230, 230, 3])

In [61]:
random_image_tensor.ndim

3